### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by msoe-sse-webmaster** [msoe-sg/msoe-sg-editor-ui#1]
As a student government admin, I would like to be able to login to the site with a google account so that I can edit content.

* AC: Given that a google user’s username is on an approved list of accounts that have permission to edit the msoe-sg website, when they enter their credentials, they are authenticated and allowed into the editor.

**Comment by andy-wojciechowski** [comment]
All development on this has been finished but a new client id needs to be generated. That will be done once I get access to the SSE admin email again
