### ISSUE TITLE
Editing the About Section

### ISSUE THREAD

**Issue by msoe-sse-webmaster** [msoe-sg/msoe-sg-editor-ui#14]
As a student government admin on the homepage, I would like to be able to edit the “About SG” section and edit the “about” part of our webpage so that site viewers can receive updated information about student government.
* AC: Given that a google user is both authorized and authenticated to the editor, and the user is on the homepage, they should see an option for editing the about page. When the click the option, make edits and hit save, then the changes to the about section are pushed into a PR on github.

**Comment by andy-wojciechowski** [comment]
This has been released.
