### ISSUE TITLE
VIew homepage on login

### ISSUE THREAD

**Issue by msoe-sse-webmaster** [msoe-sg/msoe-sg-editor-ui#2]
As a student government admin who has just signed into the editor, I would like to see a homepage with options to edit a homepage, an about page, posts and resources, so I can choose which I would like to edit.
* AC: Given that my google account is on the approved list of users and I am authenticated onto the editor, when I log on I am redirected onto the homepage with options to edit the msoe-sg homepage, about page, posts and resources.

**Comment by andy-wojciechowski** [comment]
Note this is waiting on Issue #1 to be completed before we close this.

**Comment by andy-wojciechowski** [comment]
Development has been completed on this issue and has been merged to the dev branch of the UI
